In [1]:
import pandas as pd
from shapely.geometry import Point, Polygon
from shapely import geometry
import time

In [2]:
test = pd.read_csv('../datasets/clean/clean_bike_stations.csv')
test

,id,station_name,lat,long,status,area
0,1594046383808271024,Troy St & Jackson Blvd,41.877505,-87.704850,1,27
1,641,Central Park Ave & Bloomingdale Ave,41.914166,-87.716755,1,22
2,1683527931525155814,Public Rack - Cornell Ave & 87th Pl,41.736881,-87.583146,0,48
3,367,Racine Ave & 35th St,41.830689,-87.656211,0,60
4,1673852313397164648,Public Rack - Francisco Ave & Touhy Ave,42.011865,-87.701317,0,2
...,...,...,...,...,...,...
1411,20,Sheffield Ave & Kingsbury St,41.910522,-87.653106,0,8
1412,54,Ogden Ave & Chicago Ave,41.896362,-87.654061,0,24
1413,693,Baltimore Ave & 87th St,41.737336,-87.548515,1,46
1414,718,Ewing Ave & Burnham Greenway,41.712749,-87.534814,1,52
1415,762,Green St & Randolph St*,41.883602,-87.648627,0,28

In [3]:
reference = pd.read_csv('../original_datasets/unclean_disadvantaged_areas.csv')
reference

                                              the_geom
0    MULTIPOLYGON (((-87.57366299996758 41.70796600...
1    MULTIPOLYGON (((-87.60151899995586 41.68632499...
2    MULTIPOLYGON (((-87.60036199996543 41.69284299...
3    MULTIPOLYGON (((-87.62032800000847 41.69942700...
4    MULTIPOLYGON (((-87.66036699995497 41.75771799...
..                                                 ...
275  MULTIPOLYGON (((-87.6624109999806 41.998169000...
276  MULTIPOLYGON (((-87.66572099996036 42.00497899...
277  MULTIPOLYGON (((-87.65500000001438 41.99831699...
278  MULTIPOLYGON (((-87.65029099995624 41.99662699...
279  MULTIPOLYGON (((-87.65438300000406 41.99020200...

[280 rows x 1 columns]

In [4]:
reference.dtypes

the_geom    object
dtype: object

In [5]:
reference.loc[0].values

array(['MULTIPOLYGON (((-87.57366299996758 41.707966000031426, -87.57267600000398 41.707981000009006, -87.57259999999427 41.70798300000619, -87.57051000001076 41.70801200002498, -87.56971499996679 41.70802300001818, -87.56914899998023 41.70803099997312, -87.56872800000517 41.70803700000908, -87.56860900001972 41.708037999988655, -87.56825200004245 41.70804300000275, -87.56813400001899 41.70804600003349, -87.56789199996008 41.70804999997805, -87.56716800000734 41.70806099997388, -87.56692700002974 41.708065999986964, -87.56668499999031 41.70806899996619, -87.56596000002395 41.708080000016764, -87.56571899998117 41.708085000033755, -87.56547700000543 41.708088000007386, -87.56475200001057 41.70809899998144, -87.56451100000696 41.708102999973114, -87.56432800004386 41.70810899996785, -87.56390700003448 41.70811299997787, -87.56330300003867 41.7081209999717, -87.5631990000245 41.708123000005834, -87.56269900004557 41.708129999975974, -87.56209200003089 41.70813899999696, -87.5618310000122 41.70814000000556, -87.56149100003617 41.70814499997342, -87.56088599997665 41.70815399998906, -87.56064100003277 41.70815599997372, -87.5603129999584 41.70815899996831, -87.55990600004289 41.70816400000768, -87.55966200002989 41.708168000029076, -87.5596560000119 41.70781400002581, -87.55964499996206 41.707060000021755, -87.55964500000887 41.706752000019215, -87.55964500003076 41.70639900001499, -87.55964200002931 41.70603499997233, -87.55963800002179 41.70537499997989, -87.55963299995923 41.70494600000458, -87.55962899995491 41.70458399999147, -87.5596230000245 41.70422200000641, -87.55960799999872 41.70313800000327, -87.55960300001158 41.70277699996763, -87.55932300000255 41.70277500001447, -87.55852199995525 41.702773000012385, -87.55848500004109 41.702772000034265, -87.55820599996514 41.70277199997792, -87.55819299998105 41.70277100000901, -87.55815699995749 41.70277099997703, -87.55814500004095 41.70277099998734, -87.5574979999686 41.70276800002817, -87.55744699996163 41.70276799997419, -87.55687899996877 41.70276700002591, -87.55684999999055 41.70276700002218, -87.5563010000274 41.702767000007, -87.55555799998452 41.70276699998916, -87.55491199999832 41.70276700001337, -87.55363199997193 41.70276600002601, -87.55322499996491 41.70276500001782, -87.55113399996378 41.70276500000319, -87.54871799998955 41.70276500003416, -87.5481660000065 41.702765000011645, -87.5464800000227 41.70276700000991, -87.54635700001216 41.702766999968034, -87.54634300002314 41.702767000005245, -87.54601399997311 41.70276699997405, -87.5459889999738 41.702767000003675, -87.5459050000433 41.70276700000071, -87.54586699995738 41.7027669999768, -87.54580299997096 41.70276700000664, -87.54561200000589 41.702767000013466, -87.54554900001267 41.70276700003299, -87.54547400001708 41.70276700000786, -87.54527900002651 41.702765999998675, -87.54447199996862 41.70276399997241, -87.54420299996066 41.702763999982295, -87.54412700003071 41.70276300000229, -87.54389899999751 41.70276299998732, -87.54382300001738 41.702762999973444, -87.5440849999968 41.70241200001567, -87.54487000000077 41.70135899996764, -87.54513300002913 41.70100900001634, -87.54514499996941 41.700983999979805, -87.54518399998975 41.70090899999355, -87.54519700000198 41.700884999979955, -87.54518999997813 41.700010000021926, -87.54518900001432 41.69979999998917, -87.5451680000376 41.69654700002845, -87.54516099996769 41.69546300001461, -87.54516300002217 41.69513899997279, -87.5451699999769 41.69416900000474, -87.54517300003114 41.69384599998889, -87.54519699999217 41.69203700001938, -87.54522199997918 41.690302000033896, -87.54518900000274 41.688113000011434, -87.5452049999715 41.68662500001352, -87.5452039999696 41.6866130000302, -87.54512700000292 41.68480699996887, -87.54512700003669 41.6843919999943, -87.54512700000863 41.68359800000191, -87.54512800003539 41.68314700002767, -87.5451290000054 41.68273299996605, -87.54512600003913 41.68237299999965, -87.54511699996755 41.68129599999958, -87.54511399997894 41.680936999978485, -87.54511599997967 41.67951400001873, -87.54512399995748 41.67524800000949, -87.54512799996229 41.67382599999573, -87.54538899996467 41.67266400001144, -87.54617300000291 41.66917800000776, -87.54643500002074 41.668016999971584, -87.54643299995502 41.66778000001793, -87.54642700003293 41.66707000000033, -87.54642600004068 41.66683400003113, -87.54643200001331 41.666551000015545, -87.54645100000943 41.66570299997563, -87.5464540000333 41.66557500002674, -87.54645699995707 41.66542100000882, -87.54645400001752 41.66526500000057, -87.54644699997496 41.66479699998893, -87.54644500000907 41.66464199998633, -87.54644200003871 41.66428099998743, -87.5464330000412 41.6631990000305, -87.54642999998146 41.66283899997895, -87.54641299999423 41.66245100001981, -87.54637700001935 41.66162199998064, -87.54633199998307 41.66129299998983, -87.54633199999088 41.66129200002098, -87.54628800001866 41.661117000004566, -87.5462119999832 41.660925999972726, -87.54607099999663 41.66062000001049, -87.54598599996267 41.66048600000415, -87.5458349999548 41.660243999985795, -87.54563599996469 41.65995400003264, -87.54536799996265 41.65967300002617, -87.54499500001928 41.65940400001661, -87.54459400001501 41.65911499998066, -87.54483200004347 41.65924100001218, -87.54500999999189 41.65933600002272, -87.54552700001712 41.65965599996937, -87.5457569999954 41.65979799997116, -87.5460360000105 41.659958999977974, -87.54687400002439 41.66044200002097, -87.54715399998584 41.66060300003172, -87.54727300000255 41.66066900000043, -87.54763100003878 41.66086800000151, -87.54775100002102 41.66093499996691, -87.54783700002305 41.660980999993775, -87.54809600003881 41.661119999970595, -87.54818299999174 41.6611670000208, -87.54845399999557 41.66131999997716, -87.5492699999939 41.6617790000012, -87.549542000042 41.66193299999108, -87.54978699996872 41.66207999997563, -87.55052500002745 41.66252399997434, -87.55077099997452 41.66267300000621, -87.55090199997102 41.66275399998511, -87.55129600001982 41.66299699999561, -87.55142799997294 41.66307800000193, -87.5515310000088 41.66314200003438, -87.55177200000377 41.66329200003077, -87.55183600002889 41.6633419999818, -87.55193300003216 41.6634179999875, -87.5519429999826 41.66342600000691, -87.55197300003259 41.66344999999261, -87.55198400000519 41.663458999983376, -87.55244899999178 41.66389499998912, -87.55271300003581 41.66419600002987, -87.55296700000414 41.66453700000392, -87.55308700001896 41.66471500000984, -87.55323500002682 41.66494300003154, -87.55386799999152 41.665830000027135, -87.55419599997586 41.6663370000129, -87.55432300001044 41.66653900002676, -87.55446000003506 41.66680400000197, -87.55446499997178 41.66684499999259, -87.5544099999682 41.66709099999902, -87.55480900003585 41.667742000008616, -87.5560080000179 41.66969500003067, -87.55640800004376 41.67034700002622, -87.55645899997833 41.67031700002454, -87.55648100000742 41.670261999983516, -87.55645200002063 41.67011400002369, -87.55662799999067 41.67001500001156, -87.55665000003629 41.66998199997953, -87.55678599997867 41.66991699999391, -87.55684700002884 41.66988900001431, -87.55720600003089 41.66984499998217, -87.55731600004087 41.669811999970115, -87.55738200004156 41.66976200000716, -87.55751399996642 41.6695869999785, -87.55755000003434 41.66956999997159, -87.55759400000115 41.66947699999893, -87.55771899996593 41.66935600000236, -87.55781400002911 41.66921900000616, -87.55796799998987 41.66910900000404, -87.55812899995888 41.66904800001691, -87.5584179999955 41.668993999998115, -87.5585979999659 41.66896099997595, -87.55868599996315 41.66895500000419, -87.55904399998957 41.66895499998939, -87.55907699996702 41.6689570000179, -87.55911300000261 41.668959000007014, -87.55922100004433 41.668966999979354, -87.55925700000489 41.66897000002803, -87.55925999996543 41.66854300000364, -87.55926099996013 41.668515000018004, -87.55926899998119 41.66788300003211, -87.55926899998936 41.667262000017466, -87.5592690000349 41.666836000008246, -87.55926900001192 41.66639500002972, -87.5592690000457 41.66636399998011, -87.5592700000084 41.665073999980294, -87.55927100002893 41.66463399998605, -87.55927199995821 41.66427800001098, -87.55927499995794 41.663210000025245, -87.55927599999768 41.66285400003254, -87.55927600001883 41.662804000003746, -87.55927599999214 41.66277999999226, -87.55927599999279 41.662560999979014, -87.55927700000028 41.66248799998396, -87.55927699999005 41.66223899999428, -87.55927899996075 41.661493000021444, -87.55928099996667 41.6612449999808, -87.5592820000214 41.660934999967495, -87.55928199998854 41.66083300000596, -87.55928399998385 41.65960000000966, -87.55928600004437 41.65918899996804, -87.55962699998315 41.6591749999913, -87.55963599997683 41.6591749999943, -87.56065199996024 41.659165999985255, -87.56099400003399 41.659163000009, -87.56100800000168 41.65916300002203, -87.5610529999643 41.65916299996958, -87.56106799998214 41.65916299997123, -87.56114400002944 41.659163000013265, -87.56323200001867 41.659170000030166, -87.56324100001267 41.65917000002529, -87.56557800000917 41.65917599998405, -87.56784000000704 41.65918200001448, -87.56976299998938 41.65918600000951, -87.57015600001206 41.65918699996742, -87.57123599997485 41.6591949999858, -87.57193700001997 41.659197000026836, -87.57197899995897 41.65919699997245, -87.5720880000081 41.659196999986506, -87.57254199996605 41.65919799998145, -87.57255700002831 41.659199000031805, -87.57269400004373 41.65919899997158, -87.57275599999495 41.65919899998747, -87.57294200003294 41.65919899997276, -87.57300400002309 41.65920000003092, -87.57333999996712 41.65920099999862, -87.57414100000798 41.659202000011696, -87.57550399999471 41.65920499999998, -87.57634799998823 41.65919900002294, -87.57655500000182 41.6591930000264, -87.57694700000852 41.65918300000672, -87.57745200001166 41.659193999979685, -87.57755199997996 41.65919399997633, -87.57869000002913 41.65919400000668, -87.57962700002267 41.65919400001783, -87.57978700003623 41.65919400003031, -87.58066199997046 41.659199000033084, -87.58138699995575 41.65921199999051, -87.58192700004406 41.65924100003333, -87.58230500003303 41.65927699998709, -87.58243500001574 41.6592979999924, -87.58279500002317 41.65935699998046, -87.58335300000213 41.65948700000768, -87.58359899996542 41.659546999980805, -87.5837160000223 41.659581999973845, -87.58391199995482 41.65964099997651, -87.58478599999295 41.659943000022366, -87.58497400003887 41.66000899996727, -87.5851460000251 41.660052999980444, -87.58552599998944 41.660149000028355, -87.5858289999596 41.66021200002681, -87.58589299998293 41.660225999990125, -87.5862950000069 41.66029500003406, -87.58673200000761 41.66034900000137, -87.5871500000355 41.660376999982915, -87.58787900001329 41.66039299998009, -87.58792199999807 41.660391999998815, -87.58862400000618 41.660391000008936, -87.58875400000746 41.66038999997357, -87.58899800000431 41.66039000000209, -87.58914099999 41.66038900001487, -87.58914700002858 41.660387999992786, -87.5892780000116 41.66038799997786, -87.5893879999847 41.66051599997347, -87.58941200003528 41.66054500001528, -87.58981600002484 41.6610160000338, -87.58995100000185 41.66117399996888, -87.590242000029 41.66152100000197, -87.59044399995983 41.66176300001873, -87.59112899995445 41.6625519999859, -87.59142699998603 41.66289500001872, -87.59149599998644 41.66297600001832, -87.59170599998626 41.66321899997962, -87.59174899999854 41.66326800001205, -87.59177600002232 41.66330099998711, -87.59180599997961 41.66333599997112, -87.59207399995422 41.66364900001056, -87.59270699997592 41.66439499996778, -87.59388500003385 41.665754000022446, -87.59391699998501 41.66579200000799, -87.59455700001699 41.666539999967284, -87.5956160000278 41.667766000011305, -87.59588299997421 41.66807299999062, -87.59593500002396 41.66814100001437, -87.5965730000227 41.66887200002658, -87.59717399996399 41.669582000020434, -87.59742399995882 41.66987799997739, -87.59844300002831 41.67106600001632, -87.59854599998802 41.67118699997962, -87.59861700001252 41.67125599999988, -87.59980600000914 41.67263699998842, -87.60019499999407 41.673091000016505, -87.60033399996186 41.67327200002017, -87.60045700003086 41.67343200003153, -87.60074099996815 41.67385000000792, -87.60085299997976 41.67403300001872, -87.6009710000348 41.67424100003146, -87.60102399997534 41.674339000027544, -87.60113400002066 41.674562000004705, -87.60127900001191 41.67488599997233, -87.60130600003012 41.67496800000556, -87.60144599999568 41.67533799997409, -87.60154400000384 41.67566699998362, -87.60161199999926 41.67596200003098, -87.6016640000356 41.67623999997733, -87.6017089999931 41.67657199996726, -87.6017329999594 41.676896000013606, -87.60175099996825 41.677661999967206, -87.60175500000307 41.67780000003438, -87.60177300003417 41.678293999995724, -87.60183400001524 41.68027700002673, -87.60186600002174 41.68158399997162, -87.60187299999416 41.68183299999581, -87.60187800000938 41.6824920000268, -87.60187899999366 41.68259999999131, -87.60190999996514 41.68317299998029, -87.60193200001048 41.6838079999716, -87.60194800002513 41.68405500002187, -87.6019540000177 41.68414400003011, -87.60193600003052 41.68474200003182, -87.60189999997198 41.68506200001428, -87.60176100000457 41.68569000001065, -87.60172000002244 41.685836999972274, -87.60162299997211 41.686087000024386, -87.6016010000249 41.68613799997029, -87.6015800000175 41.686187000034145, -87.60156499997613 41.68622099997352, -87.6015430000268 41.686271999975595, -87.60151999997004 41.686324999985956, -87.60151899995586 41.68632499999864, -87.60136800000103 41.686666999975074, -87.60130999999993 41.68677099997571, -87.60097399999925 41.68742299998499, -87.60069399995767 41.68796099998861, -87.60059499999177 41.68813800000078, -87.60039699995818 41.68850000002441, -87.6003419999696 41.68860199996973, -87.60029599996989 41.688676999971364, -87.6001160000203 41.68902699998347, -87.59981399998968 41.689593999972494, -87.5997369999988 41.689740000028, -87.5996130000316 41.68995599997442, -87.59957399998714 41.69002400000399, -87.59909799995519 41.69087099996558, -87.59885599999865 41.69130900001307, -87.59870900004024 41.69160100000208, -87.59834800001788 41.69227000000498, -87.59828999999357 41.69236800001501, -87.59823899998536 41.69246399996988, -87.59806699997539 41.69278600001809, -87.59724699997705 41.69430900001774, -87.5970320000353 41.6947299999992, -87.59701100000821 41.69477200001058, -87.59675099996312 41.69525899998867, -87.5964059999651 41.69587300000954, -87.59617400001144 41.69630400002773, -87.59584899996044 41.69690799997003, -87.59520800001829 41.69807400001092, -87.59513800004214 41.69821000000219, -87.59484999999803 41.69876200001549, -87.59457800004515 41.69893099997237, -87.59443000002322 41.69918200000948, -87.59431000003595 41.69937899999151, -87.59388599998096 41.700081999989145, -87.5935050000196 41.70072099998028, -87.59323899997437 41.701170000023346, -87.59293200000458 41.70094200000291, -87.59242899997832 41.70188700002711, -87.59235100000721 41.702038000009615, -87.59225100002573 41.702232999968885, -87.59219200001468 41.70235800002952, -87.5920720000088 41.702644000022744, -87.592005999991 41.70282999997878, -87.59196200000018 41.70299900002162, -87.59192799999214 41.70313400002287, -87.59180900002781 41.70321799998091, -87.59062299998237 41.704034000013635, -87.58901699996066 41.70513099999661, -87.58860499998575 41.70538800001336, -87.5882869999657 41.70558699999455, -87.58793599997968 41.705849999981304, -87.58772700003031 41.706007999972584, -87.58748799999657 41.70619699998921, -87.58742999997129 41.70624700002096, -87.58719999999683 41.70645000003052, -87.5870720000167 41.706573999971184, -87.5871170000387 41.70680899997235, -87.5872540000251 41.70751399997145, -87.58729999998727 41.7077500000075, -87.58705000000631 41.707753000003315, -87.58630000002513 41.70776200001966, -87.58614499998923 41.70776399999976, -87.58605100002896 41.70776500002002, -87.58593899997493 41.70776600000728, -87.58588400003977 41.707767000031154, -87.58584699996905 41.70776699996986, -87.58574999996995 41.7077679999885, -87.58573400002068 41.70776799997682, -87.58563999995758 41.707769000003196, -87.5851809999886 41.70777299997175, -87.58478399997635 41.7077829999935, -87.58446800003621 41.7077919999993, -87.58432000003359 41.707795000010506, -87.58387800001259 41.70780499996807, -87.58373100003732 41.70780900001002, -87.58332899996222 41.70781800002257, -87.58212499996708 41.70784500003044, -87.5817239999717 41.70785499996569, -87.5815180000352 41.70785599997465, -87.58090000003703 41.707860999972034, -87.58069500001767 41.707863000006164, -87.5806199999772 41.70786299999673, -87.5757520000286 41.70793500001258, -87.5748859999838 41.7079479999831, -87.57475900001432 41.70794899997911, -87.57437999996411 41.707953999975594, -87.57425399996156 41.70795699997217, -87.57413500000813 41.70795799998123, -87.5738789999838 41.70796300000167, -87.57378100001151 41.70796399997793, -87.57399919124248 41.70776960542184, -87.57366299996758 41.707966000031426)))'],
      dtype=object)

In [6]:
def convert_to_polygon(df):
    updated_polygons = []
    for row in df['the_geom']:
        target = row.replace('MULTIPOLYGON (((', '').replace(')))', '')
        points = target.split(', ')
        final = []
        for point in points:
            temp = point.split(' ')
            tup = float(temp[1].replace(')', '').replace('(', '')), float(temp[0].replace(')', '').replace('(', '')) 
            final.append(tup)
        polygons = Polygon(final)
        updated_polygons.append(polygons)
    return updated_polygons

In [7]:
unclean_areas = pd.read_csv('../original_datasets/unclean_areas.csv')
unclean_areas

,the_geom,PERIMETER,AREA,COMAREA_,COMAREA_ID,AREA_NUMBE,COMMUNITY,AREA_NUM_1,SHAPE_AREA,SHAPE_LEN
0,MULTIPOLYGON (((-87.60914087617894 41.84469250...,0,0,0,0,35,DOUGLAS,35,4.600462e+07,31027.054510
1,MULTIPOLYGON (((-87.59215283879394 41.81692934...,0,0,0,0,36,OAKLAND,36,1.691396e+07,19565.506153
2,MULTIPOLYGON (((-87.62879823733725 41.80189303...,0,0,0,0,37,FULLER PARK,37,1.991670e+07,25339.089750
3,MULTIPOLYGON (((-87.6067081256125 41.816813770...,0,0,0,0,38,GRAND BOULEVARD,38,4.849250e+07,28196.837157
4,MULTIPOLYGON (((-87.59215283879394 41.81692934...,0,0,0,0,39,KENWOOD,39,2.907174e+07,23325.167906
...,...,...,...,...,...,...,...,...,...,...
72,MULTIPOLYGON (((-87.69645961375822 41.70714491...,0,0,0,0,74,MOUNT GREENWOOD,74,7.558429e+07,48665.130539
73,MULTIPOLYGON (((-87.64215204651398 41.68508211...,0,0,0,0,75,MORGAN PARK,75,9.187734e+07,46396.419362
74,MULTIPOLYGON (((-87.83658087874365 41.98639611...,0,0,0,0,76,OHARE,76,3.718356e+08,173625.984660
75,MULTIPOLYGON (((-87.65455590025104 41.99816614...,0,0,0,0,77,EDGEWATER,77,4.844999e+07,31004.830946
76,MULTIPOLYGON (((-87.80675853375328 42.00083736...,0,0,0,0,9,EDISON PARK,9,3.163631e+07,25937.226841

In [8]:
unclean_areas = unclean_areas[['the_geom', 'AREA_NUMBE']]
unclean_areas

                                             the_geom  AREA_NUMBE
0   MULTIPOLYGON (((-87.60914087617894 41.84469250...          35
1   MULTIPOLYGON (((-87.59215283879394 41.81692934...          36
2   MULTIPOLYGON (((-87.62879823733725 41.80189303...          37
3   MULTIPOLYGON (((-87.6067081256125 41.816813770...          38
4   MULTIPOLYGON (((-87.59215283879394 41.81692934...          39
..                                                ...         ...
72  MULTIPOLYGON (((-87.69645961375822 41.70714491...          74
73  MULTIPOLYGON (((-87.64215204651398 41.68508211...          75
74  MULTIPOLYGON (((-87.83658087874365 41.98639611...          76
75  MULTIPOLYGON (((-87.65455590025104 41.99816614...          77
76  MULTIPOLYGON (((-87.80675853375328 42.00083736...           9

[77 rows x 2 columns]

In [9]:
unclean_areas.sort_values(by='AREA_NUMBE')

                                             the_geom  AREA_NUMBE
9   MULTIPOLYGON (((-87.65455590025104 41.99816614...           1
19  MULTIPOLYGON (((-87.6846530946559 42.019484772...           2
30  MULTIPOLYGON (((-87.64102430213292 41.95480280...           3
5   MULTIPOLYGON (((-87.6744075678037 41.976103404...           4
47  MULTIPOLYGON (((-87.67336415409336 41.93234274...           5
..                                                ...         ...
71  MULTIPOLYGON (((-87.63373383514987 41.72885272...          73
72  MULTIPOLYGON (((-87.69645961375822 41.70714491...          74
73  MULTIPOLYGON (((-87.64215204651398 41.68508211...          75
74  MULTIPOLYGON (((-87.83658087874365 41.98639611...          76
75  MULTIPOLYGON (((-87.65455590025104 41.99816614...          77

[77 rows x 2 columns]

In [10]:
clean_areas = convert_to_polygon(unclean_areas)
clean_areas

[<POLYGON ((41.845 -87.609, 41.845 -87.609, 41.845 -87.609, 41.845 -87.609, 4...>,
 <POLYGON ((41.817 -87.592, 41.817 -87.592, 41.817 -87.595, 41.817 -87.595, 4...>,
 <POLYGON ((41.802 -87.629, 41.802 -87.629, 41.802 -87.629, 41.801 -87.629, 4...>,
 <POLYGON ((41.817 -87.607, 41.817 -87.607, 41.816 -87.607, 41.816 -87.607, 4...>,
 <POLYGON ((41.817 -87.592, 41.817 -87.592, 41.817 -87.592, 41.817 -87.592, 4...>,
 <POLYGON ((41.976 -87.674, 41.976 -87.674, 41.976 -87.674, 41.975 -87.674, 4...>,
 <POLYGON ((41.786 -87.606, 41.786 -87.606, 41.786 -87.606, 41.786 -87.607, 4...>,
 <POLYGON ((41.803 -87.58, 41.802 -87.58, 41.802 -87.58, 41.802 -87.58, 41.80...>,
 <POLYGON ((41.786 -87.577, 41.786 -87.577, 41.786 -87.577, 41.786 -87.577, 4...>,
 <POLYGON ((41.998 -87.655, 41.998 -87.656, 41.998 -87.656, 41.998 -87.656, 4...>,
 <POLYGON ((41.968 -87.753, 41.968 -87.753, 41.968 -87.753, 41.968 -87.753, 4...>,
 <POLYGON ((42.005 -87.769, 42.005 -87.769, 42.005 -87.769, 42.005 -87.769, 4...>,
 <POLYGON ((41.983 -87.707, 41.983 -87.707, 41.983 -87.707, 41.983 -87.707, 4...>,
 <POLYGON ((41.974 -87.704, 41.974 -87.704, 41.973 -87.704, 41.973 -87.704, 4...>,
 <POLYGON ((41.968 -87.753, 41.968 -87.752, 41.968 -87.752, 41.968 -87.752, 4...>,
 <POLYGON ((41.961 -87.695, 41.961 -87.695, 41.961 -87.695, 41.961 -87.695, 4...>,
 <POLYGON ((41.938 -87.776, 41.938 -87.777, 41.938 -87.777, 41.938 -87.778, 4...>,
 <POLYGON ((41.918 -87.789, 41.918 -87.792, 41.919 -87.793, 41.919 -87.794, 4...>,
 <POLYGON ((41.914 -87.741, 41.914 -87.742, 41.914 -87.742, 41.914 -87.743, 4...>,
 <POLYGON ((42.019 -87.685, 42.019 -87.685, 42.019 -87.685, 42.019 -87.685, 4...>,
 <POLYGON ((41.932 -87.731, 41.932 -87.731, 41.932 -87.731, 41.931 -87.731, 4...>,
 <POLYGON ((41.936 -87.688, 41.936 -87.688, 41.936 -87.688, 41.936 -87.688, 4...>,
 <POLYGON ((41.932 -87.683, 41.932 -87.683, 41.932 -87.683, 41.931 -87.682, 4...>,
 <POLYGON ((41.888 -87.692, 41.888 -87.695, 41.888 -87.695, 41.888 -87.695, 4...>,
 <POLYGON ((41.911 -87.657, 41.911 -87.657, 41.911 -87.657, 41.91 -87.658, 41...>,
 <POLYGON ((41.918 -87.789, 41.917 -87.789, 41.917 -87.789, 41.917 -87.789, 4...>,
 <POLYGON ((41.87 -87.72, 41.87 -87.72, 41.869 -87.72, 41.869 -87.72, 41.869 ...>,
 <POLYGON ((41.888 -87.692, 41.888 -87.69, 41.888 -87.689, 41.888 -87.689, 41...>,
 <POLYGON ((41.886 -87.638, 41.886 -87.638, 41.886 -87.638, 41.886 -87.638, 4...>,
 <POLYGON ((41.87 -87.72, 41.87 -87.72, 41.87 -87.719, 41.87 -87.719, 41.87 -...>,
 <POLYGON ((41.955 -87.641, 41.955 -87.644, 41.955 -87.644, 41.955 -87.644, 4...>,
 <POLYGON ((41.835 -87.687, 41.835 -87.688, 41.835 -87.688, 41.834 -87.688, 4...>,
 <POLYGON ((41.858 -87.635, 41.857 -87.635, 41.857 -87.635, 41.856 -87.636, 4...>,
 <POLYGON ((41.845 -87.609, 41.845 -87.609, 41.845 -87.609, 41.845 -87.609, 4...>,
 <POLYGON ((41.846 -87.629, 41.846 -87.629, 41.846 -87.63, 41.846 -87.63, 41....>,
 <POLYGON ((41.997 -87.78, 41.997 -87.78, 41.997 -87.782, 41.997 -87.782, 41....>,
 <POLYGON ((41.912 -87.624, 41.911 -87.625, 41.911 -87.625, 41.911 -87.625, 4...>,
 <POLYGON ((41.889 -87.609, 41.889 -87.609, 41.889 -87.608, 41.889 -87.608, 4...>,
 <POLYGON ((41.755 -87.544, 41.755 -87.544, 41.754 -87.545, 41.754 -87.545, 4...>,
 <POLYGON ((41.737 -87.595, 41.737 -87.595, 41.737 -87.596, 41.737 -87.597, 4...>,
 <POLYGON ((41.752 -87.586, 41.751 -87.585, 41.751 -87.584, 41.75 -87.584, 41...>,
 <POLYGON ((41.755 -87.544, 41.755 -87.544, 41.755 -87.544, 41.755 -87.544, 4...>,
 <POLYGON ((41.723 -87.587, 41.723 -87.587, 41.723 -87.587, 41.723 -87.587, 4...>,
 <POLYGON ((41.823 -87.656, 41.823 -87.656, 41.823 -87.657, 41.823 -87.657, 4...>,
 <POLYGON ((41.955 -87.641, 41.955 -87.641, 41.955 -87.641, 41.955 -87.641, 4...>,
 <POLYGON ((41.723 -87.546, 41.723 -87.546, 41.723 -87.546, 41.723 -87.546, 4...>,
 <POLYGON ((41.723 -87.604, 41.722 -87.604, 41.722 -87.604, 41.722 -87.604, 4...>,
 <POLYGON ((41.932 -87.673, 41.932 -87.673, 41.932 -87.674, 41.932 -87.674, 4...>,
 <POLYGON ((41.686 -87.602, 41.686 -87.602, 41.686 -87.602, 41.686 -87.602, 4...>,
 <POLYGON ((41.723 -87.546, 41.723 -87.546, 41.723 -87.545, 41.723 -87.545, 4...>,
 <POLYGON ((41.692 -87.525, 41.692 -87.525, 41.692 -87.525, 41.692 -87.525, 4...>,
 <POLYGON ((41.659 -87.618, 41.659 -87.618, 41.659 -87.618, 41.659 -87.618, 4...>,
 <POLYGON ((41.686 -87.602, 41.686 -87.602, 41.686 -87.602, 41.686 -87.602, 4...>,
 <POLYGON ((41.692 -87.525, 41.689 -87.525, 41.689 -87.525, 41.688 -87.525, 4...>,
 <POLYGON ((41.819 -87.739, 41.819 -87.739, 41.819 -87.739, 41.818 -87.739, 4...>,
 <POLYGON ((41.826 -87.714, 41.826 -87.714, 41.826 -87.714, 41.826 -87.714, 4...>,
 <POLYGON ((41.823 -87.684, 41.823 -87.684, 41.823 -87.684, 41.823 -87.684, 4...>,
 <POLYGON ((41.824 -87.634, 41.824 -87.634, 41.824 -87.634, 41.824 -87.635, 4...>,
 <POLYGON ((41.794 -87.635, 41.794 -87.636, 41.794 -87.637, 41.794 -87.638, 4...>,
 <POLYGON ((41.804 -87.714, 41.803 -87.714, 41.802 -87.714, 41.801 -87.714, 4...>,
 <POLYGON ((41.794 -87.679, 41.794 -87.679, 41.794 -87.679, 41.794 -87.679, 4...>,
 <POLYGON ((41.786 -87.738, 41.786 -87.738, 41.786 -87.738, 41.785 -87.738, 4...>,
 <POLYGON ((41.757 -87.713, 41.757 -87.713, 41.757 -87.713, 41.757 -87.713, 4...>,
 <POLYGON ((41.758 -87.678, 41.758 -87.679, 41.758 -87.679, 41.758 -87.679, 4...>,
 <POLYGON ((41.794 -87.655, 41.794 -87.655, 41.794 -87.655, 41.794 -87.655, 4...>,
 <POLYGON ((41.783 -87.628, 41.783 -87.628, 41.783 -87.628, 41.783 -87.629, 4...>,
 <POLYGON ((41.78 -87.616, 41.78 -87.616, 41.78 -87.616, 41.78 -87.616, 41.78...>,
 <POLYGON ((41.933 -87.632, 41.933 -87.632, 41.933 -87.632, 41.932 -87.632, 4...>,
 <POLYGON ((41.757 -87.713, 41.757 -87.713, 41.757 -87.712, 41.757 -87.712, 4...>,
 <POLYGON ((41.756 -87.64, 41.756 -87.64, 41.756 -87.64, 41.756 -87.64, 41.75...>,
 <POLYGON ((41.736 -87.673, 41.732 -87.67, 41.731 -87.669, 41.73 -87.668, 41....>,
 <POLYGON ((41.729 -87.634, 41.727 -87.634, 41.727 -87.634, 41.726 -87.634, 4...>,
 <POLYGON ((41.707 -87.696, 41.706 -87.696, 41.703 -87.696, 41.703 -87.696, 4...>,
 <POLYGON ((41.685 -87.642, 41.685 -87.642, 41.685 -87.643, 41.685 -87.643, 4...>,
 <POLYGON ((41.986 -87.837, 41.986 -87.837, 41.985 -87.837, 41.985 -87.837, 4...>,
 <POLYGON ((41.998 -87.655, 41.998 -87.655, 41.998 -87.655, 41.998 -87.654, 4...>,
 <POLYGON ((42.001 -87.807, 42.001 -87.807, 42 -87.807, 42 -87.807, 42 -87.80...>]

In [11]:
clean_reference = convert_to_polygon(reference)
clean_reference

[<POLYGON ((41.708 -87.574, 41.708 -87.573, 41.708 -87.573, 41.708 -87.571, 4...>,
 <POLYGON ((41.686 -87.602, 41.686 -87.602, 41.686 -87.602, 41.686 -87.602, 4...>,
 <POLYGON ((41.693 -87.6, 41.693 -87.601, 41.693 -87.601, 41.693 -87.601, 41....>,
 <POLYGON ((41.699 -87.62, 41.699 -87.62, 41.699 -87.619, 41.699 -87.619, 41....>,
 <POLYGON ((41.758 -87.66, 41.758 -87.659, 41.758 -87.659, 41.758 -87.659, 41...>,
 <POLYGON ((41.716 -87.633, 41.717 -87.633, 41.717 -87.633, 41.718 -87.633, 4...>,
 <POLYGON ((41.698 -87.623, 41.697 -87.623, 41.697 -87.623, 41.697 -87.623, 4...>,
 <POLYGON ((41.707 -87.632, 41.707 -87.632, 41.707 -87.632, 41.707 -87.633, 4...>,
 <POLYGON ((41.699 -87.656, 41.699 -87.656, 41.699 -87.657, 41.699 -87.657, 4...>,
 <POLYGON ((41.689 -87.661, 41.689 -87.661, 41.689 -87.661, 41.689 -87.662, 4...>,
 <POLYGON ((41.691 -87.642, 41.691 -87.642, 41.692 -87.642, 41.692 -87.642, 4...>,
 <POLYGON ((41.785 -87.669, 41.785 -87.669, 41.783 -87.669, 41.783 -87.669, 4...>,
 <POLYGON ((41.692 -87.632, 41.692 -87.632, 41.692 -87.631, 41.693 -87.63, 41...>,
 <POLYGON ((41.664 -87.622, 41.665 -87.622, 41.665 -87.622, 41.666 -87.622, 4...>,
 <POLYGON ((41.685 -87.62, 41.685 -87.62, 41.685 -87.619, 41.685 -87.618, 41....>,
 <POLYGON ((41.678 -87.655, 41.678 -87.657, 41.678 -87.657, 41.678 -87.657, 4...>,
 <POLYGON ((41.656 -87.619, 41.656 -87.619, 41.657 -87.619, 41.658 -87.619, 4...>,
 <POLYGON ((41.69 -87.623, 41.69 -87.623, 41.69 -87.623, 41.691 -87.623, 41.6...>,
 <POLYGON ((41.679 -87.642, 41.679 -87.642, 41.679 -87.642, 41.679 -87.642, 4...>,
 <POLYGON ((41.675 -87.642, 41.676 -87.642, 41.676 -87.642, 41.676 -87.642, 4...>,
 <POLYGON ((41.745 -87.678, 41.745 -87.678, 41.745 -87.678, 41.745 -87.678, 4...>,
 <POLYGON ((41.656 -87.619, 41.656 -87.619, 41.657 -87.617, 41.657 -87.617, 4...>,
 <POLYGON ((41.671 -87.63, 41.671 -87.629, 41.671 -87.629, 41.671 -87.629, 41...>,
 <POLYGON ((41.729 -87.645, 41.729 -87.645, 41.729 -87.645, 41.729 -87.645, 4...>,
 <POLYGON ((41.721 -87.659, 41.721 -87.659, 41.721 -87.66, 41.721 -87.66, 41....>,
 <POLYGON ((41.743 -87.663, 41.743 -87.662, 41.743 -87.662, 41.743 -87.662, 4...>,
 <POLYGON ((41.75 -87.664, 41.75 -87.664, 41.75 -87.665, 41.75 -87.665, 41.75...>,
 <POLYGON ((41.729 -87.644, 41.729 -87.645, 41.729 -87.645, 41.729 -87.645, 4...>,
 <POLYGON ((41.733 -87.671, 41.735 -87.672, 41.736 -87.673, 41.736 -87.673, 4...>,
 <POLYGON ((41.723 -87.663, 41.723 -87.663, 41.722 -87.663, 41.722 -87.663, 4...>,
 <POLYGON ((41.729 -87.642, 41.729 -87.643, 41.729 -87.643, 41.729 -87.643, 4...>,
 <POLYGON ((41.749 -87.644, 41.749 -87.644, 41.749 -87.644, 41.75 -87.644, 41...>,
 <POLYGON ((41.743 -87.646, 41.743 -87.646, 41.743 -87.646, 41.743 -87.646, 4...>,
 <POLYGON ((41.75 -87.659, 41.75 -87.659, 41.75 -87.659, 41.749 -87.659, 41.7...>,
 <POLYGON ((41.743 -87.662, 41.743 -87.663, 41.743 -87.663, 41.743 -87.663, 4...>,
 <POLYGON ((41.752 -87.645, 41.752 -87.645, 41.752 -87.645, 41.752 -87.646, 4...>,
 <POLYGON ((41.756 -87.642, 41.756 -87.641, 41.756 -87.641, 41.756 -87.641, 4...>,
 <POLYGON ((41.751 -87.638, 41.751 -87.638, 41.751 -87.639, 41.751 -87.639, 4...>,
 <POLYGON ((41.765 -87.627, 41.765 -87.627, 41.765 -87.627, 41.765 -87.626, 4...>,
 <POLYGON ((41.765 -87.642, 41.765 -87.641, 41.765 -87.641, 41.765 -87.64, 41...>,
 <POLYGON ((41.752 -87.645, 41.752 -87.645, 41.752 -87.645, 41.752 -87.646, 4...>,
 <POLYGON ((41.765 -87.653, 41.765 -87.653, 41.765 -87.652, 41.765 -87.652, 4...>,
 <POLYGON ((41.771 -87.654, 41.772 -87.654, 41.772 -87.654, 41.772 -87.654, 4...>,
 <POLYGON ((41.765 -87.641, 41.765 -87.642, 41.765 -87.642, 41.765 -87.642, 4...>,
 <POLYGON ((41.778 -87.654, 41.778 -87.654, 41.777 -87.654, 41.776 -87.654, 4...>,
 <POLYGON ((41.765 -87.657, 41.765 -87.657, 41.765 -87.657, 41.765 -87.657, 4...>,
 <POLYGON ((41.758 -87.664, 41.758 -87.664, 41.758 -87.664, 41.758 -87.664, 4...>,
 <POLYGON ((41.765 -87.663, 41.765 -87.664, 41.765 -87.664, 41.765 -87.664, 4...>,
 <POLYGON ((41.765 -87.67, 41.765 -87.671, 41.765 -87.671, 41.765 -87.671, 41...>,
 <POLYGON ((41.758 -87.693, 41.758 -87.693, 41.758 -87.693, 41.759 -87.693, 4...>,
 <POLYGON ((41.772 -87.674, 41.772 -87.674, 41.772 -87.674, 41.772 -87.674, 4...>,
 <POLYGON ((41.773 -87.611, 41.773 -87.611, 41.773 -87.611, 41.773 -87.61, 41...>,
 <POLYGON ((41.765 -87.688, 41.765 -87.688, 41.765 -87.688, 41.765 -87.688, 4...>,
 <POLYGON ((41.779 -87.684, 41.779 -87.684, 41.779 -87.684, 41.779 -87.684, 4...>,
 <POLYGON ((41.779 -87.684, 41.779 -87.684, 41.779 -87.684, 41.779 -87.684, 4...>,
 <POLYGON ((41.768 -87.683, 41.769 -87.683, 41.769 -87.683, 41.77 -87.683, 41...>,
 <POLYGON ((41.781 -87.695, 41.781 -87.694, 41.781 -87.694, 41.781 -87.694, 4...>,
 <POLYGON ((41.776 -87.684, 41.776 -87.684, 41.776 -87.684, 41.776 -87.684, 4...>,
 <POLYGON ((41.805 -87.679, 41.805 -87.679, 41.805 -87.679, 41.805 -87.679, 4...>,
 <POLYGON ((41.787 -87.674, 41.787 -87.674, 41.787 -87.674, 41.786 -87.674, 4...>,
 <POLYGON ((41.772 -87.669, 41.772 -87.669, 41.772 -87.669, 41.772 -87.669, 4...>,
 <POLYGON ((41.774 -87.664, 41.774 -87.664, 41.774 -87.665, 41.774 -87.665, 4...>,
 <POLYGON ((41.779 -87.659, 41.779 -87.659, 41.779 -87.659, 41.779 -87.659, 4...>,
 <POLYGON ((41.782 -87.659, 41.782 -87.659, 41.781 -87.659, 41.781 -87.659, 4...>,
 <POLYGON ((41.78 -87.664, 41.78 -87.664, 41.779 -87.664, 41.779 -87.664, 41....>,
 <POLYGON ((41.787 -87.674, 41.787 -87.674, 41.788 -87.674, 41.788 -87.674, 4...>,
 <POLYGON ((41.794 -87.665, 41.794 -87.665, 41.794 -87.665, 41.794 -87.665, 4...>,
 <POLYGON ((41.793 -87.66, 41.793 -87.66, 41.792 -87.66, 41.792 -87.66, 41.79...>,
 <POLYGON ((41.723 -87.605, 41.723 -87.605, 41.723 -87.605, 41.723 -87.605, 4...>,
 <POLYGON ((41.725 -87.603, 41.725 -87.603, 41.724 -87.604, 41.723 -87.604, 4...>,
 <POLYGON ((41.737 -87.587, 41.737 -87.587, 41.737 -87.586, 41.737 -87.586, 4...>,
 <POLYGON ((41.724 -87.585, 41.723 -87.585, 41.723 -87.585, 41.723 -87.585, 4...>,
 <POLYGON ((41.745 -87.6, 41.745 -87.599, 41.746 -87.599, 41.746 -87.599, 41....>,
 <POLYGON ((41.78 -87.65, 41.78 -87.65, 41.78 -87.65, 41.78 -87.65, 41.78 -87...>,
 <POLYGON ((41.746 -87.612, 41.745 -87.612, 41.745 -87.612, 41.744 -87.612, 4...>,
 <POLYGON ((41.737 -87.609, 41.737 -87.609, 41.737 -87.609, 41.737 -87.609, 4...>,
 <POLYGON ((41.745 -87.599, 41.745 -87.6, 41.746 -87.6, 41.746 -87.6, 41.746 ...>,
 <POLYGON ((41.759 -87.596, 41.759 -87.596, 41.759 -87.596, 41.759 -87.596, 4...>,
 <POLYGON ((41.759 -87.608, 41.759 -87.608, 41.759 -87.608, 41.759 -87.608, 4...>,
 <POLYGON ((41.766 -87.608, 41.766 -87.608, 41.766 -87.608, 41.766 -87.608, 4...>,
 <POLYGON ((41.764 -87.606, 41.764 -87.606, 41.764 -87.606, 41.764 -87.606, 4...>,
 <POLYGON ((41.766 -87.608, 41.766 -87.608, 41.766 -87.608, 41.766 -87.608, 4...>,
 <POLYGON ((41.766 -87.615, 41.766 -87.615, 41.766 -87.616, 41.766 -87.616, 4...>,
 <POLYGON ((41.766 -87.625, 41.766 -87.625, 41.766 -87.626, 41.765 -87.626, 4...>,
 <POLYGON ((41.781 -87.659, 41.782 -87.659, 41.782 -87.659, 41.783 -87.659, 4...>,
 <POLYGON ((41.778 -87.654, 41.778 -87.654, 41.778 -87.654, 41.778 -87.654, 4...>,
 <POLYGON ((41.778 -87.63, 41.777 -87.63, 41.777 -87.63, 41.777 -87.63, 41.77...>,
 <POLYGON ((41.786 -87.621, 41.786 -87.622, 41.786 -87.622, 41.786 -87.623, 4...>,
 <POLYGON ((41.773 -87.623, 41.773 -87.623, 41.773 -87.623, 41.773 -87.623, 4...>,
 <POLYGON ((41.773 -87.615, 41.773 -87.615, 41.773 -87.615, 41.774 -87.615, 4...>,
 <POLYGON ((41.779 -87.606, 41.779 -87.606, 41.78 -87.606, 41.78 -87.606, 41....>,
 <POLYGON ((41.786 -87.621, 41.786 -87.621, 41.786 -87.621, 41.786 -87.621, 4...>,
 <POLYGON ((41.795 -87.631, 41.795 -87.631, 41.795 -87.631, 41.795 -87.631, 4...>,
 <POLYGON ((41.793 -87.65, 41.794 -87.65, 41.794 -87.65, 41.794 -87.65, 41.79...>,
 <POLYGON ((41.794 -87.65, 41.794 -87.65, 41.793 -87.65, 41.793 -87.65, 41.79...>,
 <POLYGON ((41.793 -87.66, 41.793 -87.66, 41.793 -87.66, 41.794 -87.66, 41.79...>,
 <POLYGON ((41.78 -87.65, 41.78 -87.65, 41.781 -87.65, 41.781 -87.65, 41.782 ...>,
 <POLYGON ((41.774 -87.559, 41.774 -87.566, 41.774 -87.567, 41.774 -87.567, 4...>,
 <POLYGON ((41.757 -87.54, 41.757 -87.541, 41.756 -87.542, 41.756 -87.543, 41...>,
 <POLYGON ((41.767 -87.55, 41.765 -87.548, 41.765 -87.559, 41.765 -87.559, 41...>,
 <POLYGON ((41.774 -87.566, 41.774 -87.559, 41.769 -87.552, 41.767 -87.55, 41...>,
 <POLYGON ((41.803 -87.567, 41.803 -87.567, 41.801 -87.567, 41.801 -87.581, 4...>,
 <POLYGON ((41.801 -87.593, 41.801 -87.594, 41.801 -87.594, 41.801 -87.594, 4...>,
 <POLYGON ((41.752 -87.584, 41.751 -87.585, 41.751 -87.585, 41.751 -87.585, 4...>,
 <POLYGON ((41.761 -87.576, 41.761 -87.576, 41.761 -87.576, 41.76 -87.576, 41...>,
 <POLYGON ((41.759 -87.586, 41.759 -87.586, 41.759 -87.587, 41.759 -87.587, 4...>,
 <POLYGON ((41.766 -87.575, 41.766 -87.575, 41.766 -87.576, 41.766 -87.576, 4...>,
 <POLYGON ((41.766 -87.585, 41.766 -87.585, 41.766 -87.585, 41.766 -87.585, 4...>,
 <POLYGON ((41.797 -87.67, 41.797 -87.67, 41.798 -87.67, 41.798 -87.67, 41.79...>,
 <POLYGON ((41.773 -87.589, 41.773 -87.588, 41.773 -87.587, 41.773 -87.587, 4...>,
 <POLYGON ((41.766 -87.57, 41.766 -87.569, 41.766 -87.569, 41.766 -87.569, 41...>,
 <POLYGON ((41.766 -87.585, 41.766 -87.585, 41.766 -87.585, 41.766 -87.585, 4...>,
 <POLYGON ((41.757 -87.566, 41.758 -87.566, 41.759 -87.566, 41.759 -87.566, 4...>,
 <POLYGON ((41.802 -87.66, 41.802 -87.66, 41.801 -87.66, 41.801 -87.66, 41.80...>,
 <POLYGON ((41.752 -87.553, 41.752 -87.553, 41.752 -87.553, 41.752 -87.552, 4...>,
 <POLYGON ((41.722 -87.524, 41.722 -87.524, 41.72 -87.524, 41.718 -87.524, 41...>,
 <POLYGON ((41.734 -87.55, 41.734 -87.55, 41.734 -87.549, 41.734 -87.549, 41....>,
 <POLYGON ((41.746 -87.554, 41.746 -87.554, 41.746 -87.554, 41.745 -87.554, 4...>,
 <POLYGON ((41.745 -87.545, 41.745 -87.545, 41.745 -87.544, 41.745 -87.544, 4...>,
 <POLYGON ((41.743 -87.554, 41.743 -87.554, 41.743 -87.553, 41.743 -87.553, 4...>,
 <POLYGON ((41.736 -87.564, 41.737 -87.565, 41.737 -87.566, 41.737 -87.566, 4...>,
 <POLYGON ((41.737 -87.543, 41.737 -87.543, 41.737 -87.543, 41.737 -87.543, 4...>,
 <POLYGON ((41.73 -87.555, 41.73 -87.554, 41.73 -87.554, 41.73 -87.554, 41.73...>,
 <POLYGON ((41.71 -87.543, 41.71 -87.543, 41.71 -87.543, 41.711 -87.542, 41.7...>,
 <POLYGON ((41.811 -87.67, 41.812 -87.67, 41.812 -87.67, 41.812 -87.67, 41.81...>,
 <POLYGON ((41.787 -87.564, 41.781 -87.563, 41.781 -87.57, 41.781 -87.57, 41....>,
 <POLYGON ((41.781 -87.591, 41.781 -87.591, 41.781 -87.592, 41.781 -87.592, 4...>,
 <POLYGON ((41.782 -87.596, 41.782 -87.596, 41.781 -87.596, 41.781 -87.596, 4...>,
 <POLYGON ((41.784 -87.606, 41.784 -87.606, 41.785 -87.606, 41.786 -87.606, 4...>,
 <POLYGON ((41.78 -87.606, 41.78 -87.606, 41.78 -87.607, 41.78 -87.607, 41.78...>,
 <POLYGON ((41.785 -87.616, 41.785 -87.616, 41.786 -87.616, 41.786 -87.615, 4...>,
 <POLYGON ((41.795 -87.622, 41.795 -87.623, 41.795 -87.623, 41.795 -87.624, 4...>,
 <POLYGON ((41.787 -87.619, 41.787 -87.619, 41.787 -87.62, 41.787 -87.62, 41....>,
 <POLYGON ((41.795 -87.623, 41.795 -87.623, 41.795 -87.622, 41.795 -87.622, 4...>,
 <POLYGON ((41.798 -87.623, 41.798 -87.623, 41.798 -87.623, 41.798 -87.624, 4...>,
 <POLYGON ((41.811 -87.619, 41.811 -87.619, 41.811 -87.618, 41.811 -87.618, 4...>,
 <POLYGON ((41.802 -87.62, 41.802 -87.621, 41.802 -87.621, 41.802 -87.621, 41...>,
 <POLYGON ((41.803 -87.611, 41.802 -87.611, 41.802 -87.611, 41.802 -87.612, 4...>,
 <POLYGON ((41.802 -87.611, 41.802 -87.611, 41.803 -87.611, 41.803 -87.611, 4...>,
 <POLYGON ((41.81 -87.605, 41.81 -87.604, 41.81 -87.604, 41.81 -87.604, 41.81...>,
 <POLYGON ((41.81 -87.605, 41.81 -87.605, 41.81 -87.605, 41.81 -87.606, 41.81...>,
 <POLYGON ((41.824 -87.603, 41.824 -87.604, 41.824 -87.604, 41.824 -87.604, 4...>,
 <POLYGON ((41.826 -87.608, 41.826 -87.608, 41.825 -87.608, 41.824 -87.607, 4...>,
 <POLYGON ((41.823 -87.607, 41.823 -87.607, 41.823 -87.607, 41.822 -87.607, 4...>,
 <POLYGON ((41.833 -87.617, 41.833 -87.617, 41.833 -87.617, 41.833 -87.617, 4...>,
 <POLYGON ((41.824 -87.617, 41.825 -87.617, 41.826 -87.617, 41.827 -87.617, 4...>,
 <POLYGON ((41.821 -87.617, 41.821 -87.617, 41.821 -87.617, 41.822 -87.617, 4...>,
 <POLYGON ((41.827 -87.617, 41.827 -87.617, 41.826 -87.617, 41.825 -87.617, 4...>,
 <POLYGON ((41.83 -87.627, 41.831 -87.627, 41.831 -87.627, 41.831 -87.627, 41...>,
 <POLYGON ((41.831 -87.627, 41.831 -87.627, 41.831 -87.627, 41.83 -87.627, 41...>,
 <POLYGON ((41.831 -87.633, 41.831 -87.632, 41.831 -87.632, 41.831 -87.632, 4...>,
 <POLYGON ((41.831 -87.633, 41.831 -87.633, 41.831 -87.633, 41.831 -87.634, 4...>,
 <POLYGON ((41.838 -87.629, 41.838 -87.629, 41.838 -87.63, 41.838 -87.63, 41....>,
 <POLYGON ((41.845 -87.634, 41.845 -87.634, 41.845 -87.634, 41.845 -87.634, 4...>,
 <POLYGON ((41.84 -87.636, 41.84 -87.636, 41.84 -87.636, 41.84 -87.636, 41.84...>,
 <POLYGON ((41.803 -87.67, 41.803 -87.67, 41.802 -87.67, 41.802 -87.67, 41.80...>,
 <POLYGON ((41.822 -87.617, 41.822 -87.617, 41.821 -87.617, 41.821 -87.617, 4...>,
 <POLYGON ((41.813 -87.617, 41.813 -87.617, 41.812 -87.617, 41.812 -87.617, 4...>,
 <POLYGON ((41.809 -87.623, 41.809 -87.623, 41.809 -87.624, 41.809 -87.624, 4...>,
 <POLYGON ((41.811 -87.621, 41.811 -87.622, 41.811 -87.622, 41.811 -87.623, 4...>,
 <POLYGON ((41.816 -87.626, 41.816 -87.627, 41.816 -87.627, 41.816 -87.628, 4...>,
 <POLYGON ((41.809 -87.629, 41.81 -87.629, 41.81 -87.629, 41.811 -87.629, 41....>,
 <POLYGON ((41.814 -87.636, 41.814 -87.636, 41.814 -87.636, 41.814 -87.636, 4...>,
 <POLYGON ((41.795 -87.631, 41.795 -87.631, 41.795 -87.631, 41.795 -87.631, 4...>,
 <POLYGON ((41.794 -87.645, 41.794 -87.645, 41.795 -87.645, 41.795 -87.645, 4...>,
 <POLYGON ((41.801 -87.668, 41.801 -87.669, 41.801 -87.669, 41.801 -87.669, 4...>,
 <POLYGON ((41.802 -87.646, 41.802 -87.647, 41.802 -87.648, 41.802 -87.648, 4...>,
 <POLYGON ((41.798 -87.65, 41.798 -87.65, 41.798 -87.65, 41.799 -87.65, 41.8 ...>,
 <POLYGON ((41.798 -87.65, 41.798 -87.65, 41.798 -87.65, 41.798 -87.65, 41.79...>,
 <POLYGON ((41.802 -87.66, 41.803 -87.66, 41.803 -87.66, 41.803 -87.66, 41.80...>,
 <POLYGON ((41.796 -87.655, 41.796 -87.655, 41.795 -87.655, 41.795 -87.655, 4...>,
 <POLYGON ((41.797 -87.67, 41.796 -87.67, 41.796 -87.669, 41.795 -87.669, 41....>,
 <POLYGON ((41.805 -87.679, 41.805 -87.679, 41.805 -87.679, 41.805 -87.679, 4...>,
 <POLYGON ((41.794 -87.674, 41.794 -87.674, 41.794 -87.674, 41.794 -87.675, 4...>,
 <POLYGON ((41.829 -87.705, 41.829 -87.705, 41.829 -87.705, 41.829 -87.705, 4...>,
 <POLYGON ((41.852 -87.656, 41.852 -87.657, 41.852 -87.657, 41.853 -87.656, 4...>,
 <POLYGON ((41.823 -87.704, 41.822 -87.705, 41.822 -87.705, 41.822 -87.705, 4...>,
 <POLYGON ((41.808 -87.684, 41.808 -87.685, 41.808 -87.685, 41.808 -87.685, 4...>,
 <POLYGON ((41.813 -87.753, 41.814 -87.752, 41.814 -87.752, 41.814 -87.75, 41...>,
 <POLYGON ((41.83 -87.667, 41.83 -87.667, 41.83 -87.668, 41.83 -87.668, 41.83...>,
 <POLYGON ((41.845 -87.693, 41.845 -87.692, 41.845 -87.692, 41.845 -87.692, 4...>,
 <POLYGON ((41.838 -87.663, 41.838 -87.664, 41.839 -87.664, 41.839 -87.664, 4...>,
 <POLYGON ((41.853 -87.664, 41.853 -87.664, 41.854 -87.664, 41.854 -87.664, 4...>,
 <POLYGON ((41.853 -87.65, 41.853 -87.65, 41.853 -87.65, 41.853 -87.65, 41.85...>,
 <POLYGON ((41.854 -87.664, 41.854 -87.664, 41.853 -87.664, 41.853 -87.664, 4...>,
 <POLYGON ((41.867 -87.666, 41.867 -87.666, 41.867 -87.666, 41.867 -87.666, 4...>,
 <POLYGON ((41.881 -87.678, 41.881 -87.678, 41.881 -87.677, 41.881 -87.677, 4...>,
 <POLYGON ((41.844 -87.708, 41.844 -87.708, 41.844 -87.708, 41.844 -87.709, 4...>,
 <POLYGON ((41.886 -87.667, 41.886 -87.667, 41.886 -87.667, 41.885 -87.667, 4...>,
 <POLYGON ((41.845 -87.69, 41.845 -87.691, 41.845 -87.691, 41.845 -87.692, 41...>,
 <POLYGON ((41.857 -87.688, 41.856 -87.688, 41.856 -87.688, 41.855 -87.688, 4...>,
 <POLYGON ((41.845 -87.703, 41.845 -87.704, 41.845 -87.704, 41.845 -87.704, 4...>,
 <POLYGON ((41.859 -87.688, 41.859 -87.688, 41.859 -87.689, 41.859 -87.689, 4...>,
 <POLYGON ((41.859 -87.691, 41.859 -87.69, 41.859 -87.689, 41.859 -87.689, 41...>,
 <POLYGON ((41.85 -87.699, 41.85 -87.699, 41.848 -87.699, 41.848 -87.699, 41....>,
 <POLYGON ((41.855 -87.703, 41.855 -87.703, 41.855 -87.703, 41.855 -87.703, 4...>,
 <POLYGON ((41.844 -87.709, 41.844 -87.708, 41.844 -87.708, 41.844 -87.708, 4...>,
 <POLYGON ((41.837 -87.712, 41.837 -87.712, 41.837 -87.712, 41.837 -87.712, 4...>,
 <POLYGON ((41.837 -87.719, 41.837 -87.719, 41.837 -87.719, 41.837 -87.719, 4...>,
 <POLYGON ((41.845 -87.731, 41.844 -87.731, 41.844 -87.731, 41.844 -87.731, 4...>,
 <POLYGON ((41.852 -87.724, 41.851 -87.724, 41.851 -87.723, 41.851 -87.723, 4...>,
 <POLYGON ((41.851 -87.738, 41.851 -87.739, 41.851 -87.739, 41.851 -87.739, 4...>,
 <POLYGON ((41.852 -87.724, 41.852 -87.724, 41.852 -87.724, 41.852 -87.724, 4...>,
 <POLYGON ((41.895 -87.726, 41.895 -87.726, 41.895 -87.726, 41.894 -87.726, 4...>,
 <POLYGON ((41.866 -87.719, 41.866 -87.719, 41.866 -87.719, 41.866 -87.72, 41...>,
 <POLYGON ((41.862 -87.725, 41.861 -87.725, 41.861 -87.725, 41.861 -87.725, 4...>,
 <POLYGON ((41.859 -87.717, 41.859 -87.717, 41.859 -87.717, 41.859 -87.718, 4...>,
 <POLYGON ((41.859 -87.713, 41.859 -87.713, 41.859 -87.713, 41.859 -87.713, 4...>,
 <POLYGON ((41.859 -87.703, 41.859 -87.703, 41.859 -87.703, 41.859 -87.704, 4...>,
 <POLYGON ((41.856 -87.71, 41.856 -87.71, 41.856 -87.71, 41.857 -87.709, 41.8...>,
 <POLYGON ((41.855 -87.713, 41.855 -87.714, 41.855 -87.714, 41.855 -87.714, 4...>,
 <POLYGON ((41.855 -87.713, 41.855 -87.713, 41.855 -87.713, 41.855 -87.713, 4...>,
 <POLYGON ((41.869 -87.698, 41.869 -87.698, 41.869 -87.698, 41.869 -87.697, 4...>,
 <POLYGON ((41.878 -87.696, 41.879 -87.696, 41.879 -87.696, 41.879 -87.696, 4...>,
 <POLYGON ((41.881 -87.686, 41.881 -87.686, 41.881 -87.686, 41.881 -87.686, 4...>,
 <POLYGON ((41.881 -87.686, 41.881 -87.686, 41.881 -87.686, 41.881 -87.686, 4...>,
 <POLYGON ((41.888 -87.706, 41.888 -87.706, 41.888 -87.706, 41.888 -87.705, 4...>,
 <POLYGON ((41.888 -87.706, 41.888 -87.706, 41.888 -87.706, 41.888 -87.707, 4...>,
 <POLYGON ((41.896 -87.702, 41.896 -87.702, 41.896 -87.702, 41.896 -87.702, 4...>,
 <POLYGON ((41.895 -87.716, 41.895 -87.716, 41.895 -87.716, 41.895 -87.716, 4...>,
 <POLYGON ((41.895 -87.716, 41.895 -87.717, 41.895 -87.717, 41.895 -87.717, 4...>,
 <POLYGON ((41.888 -87.721, 41.888 -87.722, 41.888 -87.722, 41.888 -87.723, 4...>,
 <POLYGON ((41.871 -87.716, 41.872 -87.716, 41.872 -87.716, 41.872 -87.716, 4...>,
 <POLYGON ((41.888 -87.714, 41.888 -87.713, 41.888 -87.713, 41.888 -87.712, 4...>,
 <POLYGON ((41.881 -87.711, 41.881 -87.711, 41.881 -87.711, 41.882 -87.711, 4...>,
 <POLYGON ((41.874 -87.706, 41.874 -87.706, 41.874 -87.706, 41.874 -87.706, 4...>,
 <POLYGON ((41.874 -87.706, 41.874 -87.706, 41.874 -87.706, 41.874 -87.706, 4...>,
 <POLYGON ((41.879 -87.696, 41.879 -87.696, 41.879 -87.696, 41.878 -87.696, 4...>,
 <POLYGON ((41.869 -87.697, 41.869 -87.698, 41.869 -87.698, 41.869 -87.698, 4...>,
 <POLYGON ((41.87 -87.701, 41.869 -87.701, 41.869 -87.701, 41.869 -87.701, 41...>,
 <POLYGON ((41.874 -87.711, 41.874 -87.711, 41.874 -87.711, 41.874 -87.711, 4...>,
 <POLYGON ((41.881 -87.711, 41.881 -87.711, 41.881 -87.711, 41.881 -87.712, 4...>,
 <POLYGON ((41.903 -87.707, 41.903 -87.707, 41.903 -87.707, 41.903 -87.707, 4...>,
 <POLYGON ((41.888 -87.722, 41.888 -87.721, 41.888 -87.721, 41.888 -87.721, 4...>,
 <POLYGON ((41.874 -87.72, 41.874 -87.72, 41.874 -87.72, 41.874 -87.72, 41.87...>,
 <POLYGON ((41.869 -87.725, 41.869 -87.725, 41.869 -87.725, 41.869 -87.725, 4...>,
 <POLYGON ((41.869 -87.725, 41.869 -87.725, 41.869 -87.725, 41.869 -87.725, 4...>,
 <POLYGON ((41.874 -87.73, 41.874 -87.73, 41.874 -87.73, 41.874 -87.73, 41.87...>,
 <POLYGON ((41.888 -87.726, 41.888 -87.726, 41.888 -87.726, 41.888 -87.726, 4...>,
 <POLYGON ((41.881 -87.741, 41.881 -87.742, 41.881 -87.742, 41.881 -87.743, 4...>,

In [12]:
def determine_within(df):
    statuses = []
    areas = []
    for i in range(len(df)):
        temp = geometry.Point(df.lat.loc[i], df.long.loc[i])
        status = 0
        for polygon in clean_reference:
            if (polygon.contains(temp)): 
                status = 1
        statuses.append(status)
        index = 0
        inside = False
        for polygon in clean_areas:
            if (polygon.contains(temp)): 
                areas.append(unclean_areas['AREA_NUMBE'].iloc[index])
                inside = True
            index += 1
        if inside == False:
            areas.append(0)
    df['status'] = statuses
    df['area'] = areas
    return df

In [13]:
test = determine_within(test)
test

,id,station_name,lat,long,status,area
0,1594046383808271024,Troy St & Jackson Blvd,41.877505,-87.704850,1,27
1,641,Central Park Ave & Bloomingdale Ave,41.914166,-87.716755,1,22
2,1683527931525155814,Public Rack - Cornell Ave & 87th Pl,41.736881,-87.583146,0,48
3,367,Racine Ave & 35th St,41.830689,-87.656211,0,60
4,1673852313397164648,Public Rack - Francisco Ave & Touhy Ave,42.011865,-87.701317,0,2
...,...,...,...,...,...,...
1411,20,Sheffield Ave & Kingsbury St,41.910522,-87.653106,0,8
1412,54,Ogden Ave & Chicago Ave,41.896362,-87.654061,0,24
1413,693,Baltimore Ave & 87th St,41.737336,-87.548515,1,46
1414,718,Ewing Ave & Burnham Greenway,41.712749,-87.534814,1,52
1415,762,Green St & Randolph St*,41.883602,-87.648627,0,28

In [14]:
test.status.value_counts()

status
0    941
1    475
Name: count, dtype: int64

In [15]:
tables = ["clean_311", "clean_bike_stations", "clean_bus_stations", "clean_crime", "clean_cta_stations"]

In [16]:
def read_in_files(tables):
    for table in tables:
        globals()[table] = pd.read_csv(f"../datasets/clean/{table}.csv")
        globals()[table] = determine_within(globals()[table])
        print(f'{table} is done')

In [17]:
#read_in_files(tables)

In [18]:
clean_bike_stations = pd.read_csv('../datasets/clean/clean_bike_stations.csv')
clean_bike_stations

,id,station_name,lat,long,status,area
0,1594046383808271024,Troy St & Jackson Blvd,41.877505,-87.704850,1,27
1,641,Central Park Ave & Bloomingdale Ave,41.914166,-87.716755,1,22
2,1683527931525155814,Public Rack - Cornell Ave & 87th Pl,41.736881,-87.583146,0,48
3,367,Racine Ave & 35th St,41.830689,-87.656211,0,60
4,1673852313397164648,Public Rack - Francisco Ave & Touhy Ave,42.011865,-87.701317,0,2
...,...,...,...,...,...,...
1411,20,Sheffield Ave & Kingsbury St,41.910522,-87.653106,0,8
1412,54,Ogden Ave & Chicago Ave,41.896362,-87.654061,0,24
1413,693,Baltimore Ave & 87th St,41.737336,-87.548515,1,46
1414,718,Ewing Ave & Burnham Greenway,41.712749,-87.534814,1,52
1415,762,Green St & Randolph St*,41.883602,-87.648627,0,28

In [19]:
clean_bike_stations = determine_within(clean_bike_stations)
clean_bike_stations

,id,station_name,lat,long,status,area
0,1594046383808271024,Troy St & Jackson Blvd,41.877505,-87.704850,1,27
1,641,Central Park Ave & Bloomingdale Ave,41.914166,-87.716755,1,22
2,1683527931525155814,Public Rack - Cornell Ave & 87th Pl,41.736881,-87.583146,0,48
3,367,Racine Ave & 35th St,41.830689,-87.656211,0,60
4,1673852313397164648,Public Rack - Francisco Ave & Touhy Ave,42.011865,-87.701317,0,2
...,...,...,...,...,...,...
1411,20,Sheffield Ave & Kingsbury St,41.910522,-87.653106,0,8
1412,54,Ogden Ave & Chicago Ave,41.896362,-87.654061,0,24
1413,693,Baltimore Ave & 87th St,41.737336,-87.548515,1,46
1414,718,Ewing Ave & Burnham Greenway,41.712749,-87.534814,1,52
1415,762,Green St & Randolph St*,41.883602,-87.648627,0,28

In [20]:
clean_bike_stations.to_csv('../datasets/clean/clean_bike_stations.csv', index=False)

In [21]:
for table in tables:
    globals()[table].to_csv(f'../datasets/clean/{table}.csv', index=False)
    print(f"Just finished saving the {table} table to csv.")

KeyError: 'clean_311'

In [ ]:
clean_police_stations = pd.read_csv('../datasets/clean/clean_police_stations.csv')
clean_police_stations

    id        lat       long
0    0  41.830702 -87.623395
1   18  41.903242 -87.643352
2   19  41.947400 -87.651512
3   20  41.979550 -87.692845
4   22  41.691435 -87.668520
5   24  41.999763 -87.671324
6   25  41.918609 -87.765574
7    1  41.858373 -87.627356
8    2  41.801811 -87.630560
9    3  41.766431 -87.605748
10   4  41.707933 -87.568349
11   5  41.692723 -87.604506
12   6  41.752137 -87.644229
13   7  41.779632 -87.660887
14   8  41.778987 -87.708864
15   9  41.837394 -87.646408
16  10  41.856685 -87.708382
17  11  41.873582 -87.705488
18  12  41.862977 -87.656973
19  14  41.921103 -87.697452
20  15  41.880083 -87.768200
21  16  41.974094 -87.766149
22  17  41.966053 -87.728115

In [ ]:
clean_police_stations = determine_within(clean_police_stations)
clean_police_stations.to_csv('../datasets/clean/clean_police_stations.csv', index=False)
clean_police_stations

    id        lat       long  status  area
0    0  41.830702 -87.623395    True    35
1   18  41.903242 -87.643352   False     8
2   19  41.947400 -87.651512   False     6
3   20  41.979550 -87.692845   False     4
4   22  41.691435 -87.668520   False    75
5   24  41.999763 -87.671324   False     1
6   25  41.918609 -87.765574   False    19
7    1  41.858373 -87.627356   False    33
8    2  41.801811 -87.630560    True    37
9    3  41.766431 -87.605748    True    42
10   4  41.707933 -87.568349    True    51
11   5  41.692723 -87.604506    True    50
12   6  41.752137 -87.644229   False    71
13   7  41.779632 -87.660887    True    67
14   8  41.778987 -87.708864   False    66
15   9  41.837394 -87.646408   False    60
16  10  41.856685 -87.708382    True    29
17  11  41.873582 -87.705488    True    27
18  12  41.862977 -87.656973    True    28
19  14  41.921103 -87.697452   False    22
20  15  41.880083 -87.768200    True    25
21  16  41.974094 -87.766149   False    11
22  17  41.966053 -87.728115   False    14

In [17]:
clean_lighting = pd.read_csv('../datasets/clean/clean_lighting.csv')
clean_lighting = determine_within(clean_lighting)
clean_lighting

,Unnamed: 0,date,id,lat,long,status,area
0,0,2010-07-06,10-01015837,41.730274,-87.659251,1,73
1,1,2010-07-07,10-01015837,41.730274,-87.659251,1,73
2,2,2010-07-08,10-01015837,41.730274,-87.659251,1,73
3,3,2010-07-09,10-01015837,41.730274,-87.659251,1,73
4,4,2010-07-10,10-01015837,41.730274,-87.659251,1,73
...,...,...,...,...,...,...,...
9118467,9118467,2019-02-05,18-03384721,41.728848,-87.637507,1,71
9118468,9118468,2019-02-06,18-03384721,41.728848,-87.637507,1,71
9118469,9118469,2019-02-07,18-03384721,41.728848,-87.637507,1,71
9118470,9118470,2019-02-08,18-03384721,41.728848,-87.637507,1,71
9118471,9118471,2019-02-09,18-03384721,41.728848,-87.637507,1,71

In [19]:
clean_lighting = clean_lighting[['date', 'id', 'lat', 'long', 'status', 'area']]

In [15]:
clean_vacant_buildings = pd.read_csv('../datasets/clean/clean_vacant_buildings.csv')
clean_vacant_buildings = determine_within(clean_vacant_buildings)
clean_vacant_buildings

,Unnamed: 0.1,Unnamed: 0,start_date,id,lat,long,end_date,duration,status,area
0,0,0,2017-10-11,17-06828959,41.753463,-87.657041,2023-10-19,2199 days,1,71
1,1,1,2017-10-11,17-06827096,41.774412,-87.611883,2023-10-19,2199 days,1,42
2,2,2,2017-10-11,17-06818719,41.702514,-87.630974,2023-10-19,2199 days,1,49
3,3,3,2017-10-11,17-06824436,41.789879,-87.643825,2023-10-19,2199 days,1,68
4,4,4,2017-10-11,17-06826684,41.721604,-87.632602,2023-10-19,2199 days,1,49
...,...,...,...,...,...,...,...,...,...,...
65114,65114,65114,2018-12-17,18-03384005,41.741764,-87.556361,2023-10-19,1767 days,1,46
65115,65115,65115,2018-12-17,18-03380438,41.744965,-87.657233,2023-10-19,1767 days,1,71
65116,65116,65116,2018-12-17,18-03379703,41.752659,-87.578451,2023-10-19,1767 days,1,43
65117,65117,65117,2018-12-17,18-03382499,41.894108,-87.726045,2023-10-19,1767 days,1,23
65118,65118,65118,2016-04-29,16-02925607,NaN,NaN,2023-10-19,2729 days,0,0

In [20]:
clean_lighting.to_csv('../datasets/clean/clean_lighting.csv', index=False)
#clean_vacant_buildings.to_csv('../datasets/clean/clean_vacant_buildings.csv', index=False)